dependencies:
- name: exposecontroller
  version: 2.3.82
  repository: http://chartmuseum.jenkins-x.io
  alias: expose
- name: exposecontroller
  version: 2.3.82
  repository: http://chartmuseum.jenkins-x.io
  alias: cleanup
- name: alfresco-content-services
  alias: acs
  version: 1.1.7
  repository: http://kubernetes-charts.alfresco.com/stable

