expose:
  Args: 
    - --v
    - 4
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded

cleanup:
  Args: 
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
expose:
  config:
    domain: 54.159.228.81.nip.io
    exposer: Ingress
    http: "true"
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded

acs:
  repository:
    replicaCount: 1
    ingress:
      path: /alfresco
    
  apiexplorer:
    ingress:
      path: /api-explorer
      
  share:
    ingress:
      path: /share
      
  alfresco-digital-workspace:
    ingress:
      path: /digital-workspace  
