expose:
  Args: 
    - --v
    - 4
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded

cleanup:
  Args: 
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
expose:
  config:
    domain: 54.159.228.81.nip.io
    exposer: Ingress
    http: "true"
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded

acs:
  # https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  registryPullSecrets: quay-io-private-registry-secret
  
  externalHost: jx-acs.54.159.228.81.nip.io
  externalProtocol: http
  externalPort: 80
  
  persistence:
    existingClaim: "alfresco-volume-claim-override"
    baseSize: 20Gi
  
  postgresql:
    enabled: true
    # Default to Postgresql PVC to avoid same volume mount conflict between ActiveMQ and Postresql
    persistence:
      existingClaim: null
    
  repository:
    replicaCount: 1
    ingress:
      path: /alfresco
    
  apiexplorer:
    ingress:
      path: /api-explorer
      
  share:
    ingress:
      path: /share
      
  alfresco-digital-workspace:
    ingress:
      path: /digital-workspace  

